# Generated by Django 4.2.7 on 2025-07-24 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_product_processor_product_ram_product_screen_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url', models.URLField()),
                ('competitor', models.CharField(choices=[('asif', 'Asif Computers'), ('paklap', 'PakLap')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('title', 'competitor')},
            },
        ),
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor', models.CharField(choices=[('asif', 'Asif Computers'), ('paklap', 'PakLap')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('products_scraped', models.IntegerField(default=0)),
                ('new_products', models.IntegerField(default=0)),
                ('updated_products', models.IntegerField(default=0)),
                ('errors', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asif_price_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paklap_price_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_compared', models.DateTimeField(auto_now=True)),
                ('match_confidence_asif', models.FloatField(default=0.0, help_text='Matching confidence score (0-1)')),
                ('match_confidence_paklap', models.FloatField(default=0.0, help_text='Matching confidence score (0-1)')),
                ('best_asif_match', models.ForeignKey(blank=True, limit_choices_to={'competitor': 'asif'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asif_comparisons', to='price_comparison.competitorproduct')),
                ('best_paklap_match', models.ForeignKey(blank=True, limit_choices_to={'competitor': 'paklap'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paklap_comparisons', to='price_comparison.competitorproduct')),
                ('seller_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_comparison', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('competitor_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='price_comparison.competitorproduct')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
