# Generated by Django 4.2.7 on 2025-07-26 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_comparison', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomparison',
            old_name='match_confidence_asif',
            new_name='match_confidence_priceoye',
        ),
        migrations.RenameField(
            model_name='productcomparison',
            old_name='asif_price_difference',
            new_name='priceoye_price_difference',
        ),
        migrations.RemoveField(
            model_name='productcomparison',
            name='best_asif_match',
        ),
        migrations.AddField(
            model_name='productcomparison',
            name='best_priceoye_match',
            field=models.ForeignKey(blank=True, limit_choices_to={'competitor': 'priceoye'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priceoye_comparisons', to='price_comparison.competitorproduct'),
        ),
        migrations.AlterField(
            model_name='competitorproduct',
            name='competitor',
            field=models.CharField(choices=[('paklap', 'PakLap'), ('priceoye', 'PriceOye')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapinglog',
            name='competitor',
            field=models.CharField(choices=[('paklap', 'PakLap'), ('priceoye', 'PriceOye')], max_length=20),
        ),
    ]
