# Generated by Django 5.2.3 on 2025-07-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('rating', models.FloatField(default=0.0)),
                ('image', models.URLField()),
                ('category', models.CharField(choices=[('laptop', 'Laptop'), ('accessory', 'Accessory'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_flash_sale', models.BooleanField(default=False)),
                ('flash_sale_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
