# Generated by Django 5.2.4 on 2025-07-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_systemsettings_notification_salesreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.CharField(blank=True, help_text='e.g., Intel Core i5, AMD Ryzen', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, help_text='e.g., 8GB, 16GB, 32GB', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_size',
            field=models.CharField(blank=True, help_text='e.g., 15.6 inch, 13.3 inch', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.CharField(blank=True, help_text='e.g., 256GB SSD, 1TB HDD', max_length=50),
        ),
    ]
