# Generated by Django 4.2.7 on 2025-07-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_processor_product_ram_product_screen_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('accessory', 'Accessory')], max_length=50),
        ),
    ]
