# Generated by Django 4.2.7 on 2025-07-27 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspendedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fraud', 'Fraudulent Activity'), ('spam', 'Spam/Inappropriate Content'), ('fake_products', 'Fake/Counterfeit Products'), ('scam', 'Scam Activities'), ('violation', 'Terms of Service Violation'), ('security_threat', 'Security Threat'), ('impersonation', 'Impersonation'), ('harmful_content', 'Harmful Content'), ('illegal_activity', 'Illegal Activity'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('suspended_at', models.DateTimeField(auto_now_add=True)),
                ('suspension_end', models.DateTimeField(blank=True, help_text='Leave empty for permanent suspension', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('suspended_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspended_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suspension', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DangerousProductReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=200)),
                ('seller_username', models.CharField(max_length=150)),
                ('seller_id', models.IntegerField()),
                ('danger_type', models.CharField(choices=[('fraud', 'Fraudulent Activity'), ('spam', 'Spam/Inappropriate Content'), ('fake_products', 'Fake/Counterfeit Products'), ('scam', 'Scam Activities'), ('violation', 'Terms of Service Violation'), ('security_threat', 'Security Threat'), ('impersonation', 'Impersonation'), ('harmful_content', 'Harmful Content'), ('illegal_activity', 'Illegal Activity'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('evidence_urls', models.TextField(blank=True, help_text='URLs to evidence (images, documents, etc.)')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_category', models.CharField(max_length=50)),
                ('product_description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('action_taken', models.CharField(blank=True, max_length=50)),
                ('action_taken_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='danger_actions', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danger_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('delete_user', 'Delete User'), ('delete_product', 'Delete Product'), ('suspend_user', 'Suspend User'), ('suspend_store', 'Suspend Store'), ('ban_user', 'Ban User'), ('delete_store', 'Delete Store'), ('mass_delete_products', 'Mass Delete Products'), ('mass_delete_users', 'Mass Delete Users')], max_length=50)),
                ('target_product_id', models.IntegerField(blank=True, null=True)),
                ('target_product_name', models.CharField(blank=True, max_length=200)),
                ('target_store_id', models.IntegerField(blank=True, null=True)),
                ('target_store_name', models.CharField(blank=True, max_length=200)),
                ('danger_reason', models.CharField(choices=[('fraud', 'Fraudulent Activity'), ('spam', 'Spam/Inappropriate Content'), ('fake_products', 'Fake/Counterfeit Products'), ('scam', 'Scam Activities'), ('violation', 'Terms of Service Violation'), ('security_threat', 'Security Threat'), ('impersonation', 'Impersonation'), ('harmful_content', 'Harmful Content'), ('illegal_activity', 'Illegal Activity'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the danger/issue')),
                ('evidence', models.TextField(blank=True, help_text='Evidence or proof of the issue')),
                ('affected_users_count', models.IntegerField(default=0)),
                ('affected_products_count', models.IntegerField(default=0)),
                ('financial_impact', models.DecimalField(decimal_places=2, default=0, help_text='Estimated financial impact', max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['admin_user', 'timestamp'], name='products_ad_admin_u_a7c474_idx'), models.Index(fields=['action_type', 'timestamp'], name='products_ad_action__ab7b7c_idx'), models.Index(fields=['danger_reason'], name='products_ad_danger__3439c8_idx')],
            },
        ),
    ]
